version: "3.9"

services:
  server:
    build: .
    ports:
      - "5004:5004"
    environment:
      - DATABASE_URL=postgres://docker:123456@db:5432/docker
  db:
    image: "postgres"
    ports:
      - "4321:5432"
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "docker"
